export const GET_EVENTS_STARTED = 'GET_EVENTS_STARTED' 
export const GET_EVENTS_COMPLETED = 'GET_EVENTS_COMPLETED' 
export const GET_EVENTS_FAILED = 'GET_EVENTS_FAILED' 

export const ADD_EVENT_STARTED = 'ADD_EVENT_STARTED' 
export const ADD_EVENT_COMPLETED = 'ADD_EVENT_COMPLETED' 
export const ADD_EVENT_FAILED = 'ADD_EVENT_FAILED' 

export const DELETE_EVENT_STARTED = 'DELETE_EVENT_STARTED' 
export const DELETE_EVENT_COMPLETED = 'DELETE_EVENT_COMPLETED' 
export const DELETE_EVENT_FAILED = 'DELETE_EVENT_FAILED' 