export const START_FETCH_INSTITUTIONS = 'START_FETCH_INSTITUTIONS';
export const FINISH_FETCH_INSTITUTIONS = 'FINISH_FETCH_INSTITUTIONS';
export const FAIL_FETCH_INSTITUTIONS = 'FAIL_FETCH_INSTITUTIONS';