
export const GET_NOTIFICATIONS_STARTED = 'GET_NOTIFICATIONS_STARTED' 
export const GET_NOTIFICATIONS_COMPLETED = 'GET_NOTIFICATIONS_COMPLETED' 
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED' 

export const ADD_NOTIFICATION_STARTED = 'ADD_NOTIFICATION_STARTED' 
export const ADD_NOTIFICATION_COMPLETED = 'ADD_NOTIFICATION_COMPLETED' 
export const ADD_NOTIFICATION_FAILED = 'ADD_NOTIFICATION_FAILED' 

export const DELETE_NOTIFICATION_STARTED = 'DELETE_NOTIFICATION_STARTED' 
export const DELETE_NOTIFICATION_COMPLETED = 'DELETE_NOTIFICATION_COMPLETED' 
export const DELETE_NOTIFICATION_FAILED = 'DELETE_NOTIFICATION_FAILED' 