
export const GET_NOTIFICATIONS_STARTED = 'GET_NOTIFICATIONS_STARTED' //Ver el horario
export const GET_NOTIFICATIONS_COMPLETED = 'GET_NOTIFICATIONS_COMPLETED' //Ver el horario
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED' //Ver el horario

export const ADD_NOTIFICATION_STARTED = 'ADD_NOTIFICATION_STARTED' //Ver el horario
export const ADD_NOTIFICATION_COMPLETED = 'ADD_NOTIFICATION_COMPLETED' //Ver el horario
export const ADD_NOTIFICATION_FAILED = 'ADD_NOTIFICATION_FAILED' //Ver el horario

export const DELETE_NOTIFICATION_STARTED = 'DELETE_NOTIFICATION_STARTED' //Ver el horario
export const DELETE_NOTIFICATION_COMPLETED = 'DELETE_NOTIFICATION_COMPLETED' //Ver el horario
export const DELETE_NOTIFICATION_FAILED = 'DELETE_NOTIFICATION_FAILED' //Ver el horario