export const GET_PROFILE_STARTED = 'GET_PROFILE_STARTED' 
export const GET_PROFILE_COMPLETED = 'GET_PROFILE_COMPLETED' 
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED' 

export const EDIT_PROFILE_STARTED = 'EDIT_PROFILE_STARTED'
export const EDIT_PROFILE_COMPLETED = 'EDIT_PROFILE_COMPLETED'
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED'