export const GET_USER_PROFILE_STARTED = 'GET_USER_PROFILE_STARTED'
export const GET_USER_PROFILE_COMPLETED = 'GET_USER_PROFILE_COMPLETED'
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED'