/*
state:
  tutor:
    id
    score
    description
    hours_done
    individual_price
    grupal_price
*/

export const GET_TUTOR_PROFILE_STARTED = 'GET_TUTOR_PROFILE_STARTED'
export const GET_TUTOR_PROFILE_COMPLETED = 'GET_TUTOR_PROFILE_COMPLETED'
export const GET_TUTOR_PROFILE_FAILED = 'GET_TUTOR_PROFILE_FAILED'

export const EDIT_TUTOR_PROFILE_STARTED = 'EDIT_TUTOR_PROFILE_STARTED'
export const EDIT_TUTOR_PROFILE_COMPLETED = 'EDIT_TUTOR_PROFILE_COMPLETED'
export const EDIT_TUTOR_PROFILE_FAILED = 'EDIT_TUTOR_PROFILE_FAILED'